# create-env-local:
# 	MARKER=local node ./envs/create-env.js

# create-env-staging:
# 	MARKER=staging node ./envs/create-env.js

ssh-into:
	ssh -i ./byqstaging.pem ubuntu@ec2-3-72-231-170.eu-central-1.compute.amazonaws.com

# deploy-front:
# 	scp -i ./deploy/byqstaging.pem -r ./build ubuntu@ec2-3-72-231-170.eu-central-1.compute.amazonaws.com:byq/byw-frontend/

# run:
# 	tmux && cd byq/byq-frontend && npm run server

# deployment:
# 	npm run build && make deploy-front && make run